services:
  - type: web
    name: mysite
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mysite.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings
      - key: PYTHON_VERSION
        value: "3.10"
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_cK2zJtlIMBH0@ep-restless-poetry-ago1z2ig-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

